[[redirects]]
  from = "/*"
  to = "/404"
  status = 404
[[headers]]
  for = "/*" # This defines which paths this specific [[headers]] block will cover.
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "frame-ancestors https://affectionate-goldberg-b7bb76.netlify.app/"
    Content-Security-Policy = "script-src https://affectionate-goldberg-b7bb76.netlify.app/"
    Content-Security-Policy = "style-src https://affectionate-goldberg-b7bb76.netlify.app/"
    Content-Security-Policy = "img-src https://affectionate-goldberg-b7bb76.netlify.app/"
    Content-Security-Policy = "connect-src https://affectionate-goldberg-b7bb76.netlify.app/"
    Content-Security-Policy = "media-src https://affectionate-goldberg-b7bb76.netlify.app/"\
    Content-Security-Policy = "object-src https://affectionate-goldberg-b7bb76.netlify.app/"
    Content-Security-Policy = "manifest-src https://affectionate-goldberg-b7bb76.netlify.app/"
    Content-Security-Policy = "worker-src https://affectionate-goldberg-b7bb76.netlify.app/"
